# Copyright 2021, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Queue next PR on pushes to master
name: PR Queue

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  notify:
    name: Notify PR candidate
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/pr-queue@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
